spring:
  # DataSource Config
  datasource:
    url: jdbc:mysql://localhost:3306/ousir?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  address: 0.0.0.0



